# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos7885.dtb
dtbo-y += exynos7904-a30_swa_open_00.dtbo
dtbo-y += exynos7904-a30_swa_open_01.dtbo
dtbo-y += exynos7904-a30_swa_open_02.dtbo

dtb-$(CONFIG_MACH_EXYNOS7885_A30) := \
	exynos7885.dtb

dtbo-$(CONFIG_MACH_EXYNOS7885_A30) := \
	exynos7904-a30_swa_open_00.dtbo \
	exynos7904-a30_swa_open_01.dtbo \
	exynos7904-a30_swa_open_02.dtbo

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
